### ISSUE TITLE
Unable to assign duration picker to a Duration field

### ISSUE THREAD

**Issue by CHTEEVE** [paulbreuler/PCF-Controls#8]
I tried, within a form and within a quick creation form to set the duration picker control for a Duration field. But the control is unvailable in the list.

I tried with the Papps interface and with the olf D365 interface.

I enabled as well usage of PCFcomponent in my tenant.
I imported the  DurationPickerCustomControl_1_2_1_managed solution and publish all customizations many times.

Any ideas?

**Comment by paulbreuler** [comment]
Unfortunately, PCF does not currently support Duration type fields. A frustrating limitation for this particular use case.

In the input manifest I have this bound to a whole number field type.

https://docs.microsoft.com/en-us/powerapps/developer/component-framework/manifest-schema-reference/property#value-elements-that-are-not-supported

**Comment by paulbreuler** [comment]
I have pushed an update to the ReadMe file to clarify.
